"""Download the inscription images from lineara.xyz, at a pinned commit.

Two per face where they exist: the GORILA facsimile drawing and a photograph.
Only the faces that get a full page are fetched, which is about 1,000 files
and 80 MB rather than the 141 MB the source holds.

BE KIND TO THE HOST. Files already on disk are never re-requested, and names
that 404 are recorded in data/images-absent.json so they are never requested
twice either -- the commit is pinned, so what is absent there stays absent.
Without that list a fully cached run still fired 1,172 pointless requests.
A warm run now makes none at all. `--force` re-probes everything.

RIGHTS. These are GORILA plate material, recorded upstream as
"© École Française d'Athènes". Downloading them for local work is one thing;
**publishing them is redistribution and needs the EFA's permission**. Nothing
here publishes anything: the files land in data/upstream/, which is
gitignored, and the site renders them only where they are present. See
docs/website-design.md, "Rights: this constrains the design".
"""

import json
import sqlite3
import urllib.error
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

from . import build as builder
from .site import IMAGE_SOURCE, ROOT

REPO = "mwenge/lineara.xyz"
COMMIT = "43fe7cf1abc8e6bb1ea3228c3a1bd5938709620a"
STAMP = "SOURCE.txt"
KINDS = {"facsimile": "Facsimile", "photograph": "Inscription"}

# Most faces have only some of the four candidate names, so most of the names
# we generate do not exist upstream. The commit is pinned, so a name absent at
# that commit is absent for good: recording which ones 404'd turns 1,172
# pointless requests per run into none. Committed, because it is a list of
# file names -- no image data -- and it spares CI the same requests on a cold
# cache. Rebuilt from scratch whenever COMMIT changes, or with --force.
ABSENT_PATH = ROOT / "data" / "images-absent.json"


def _url(name):
    return "https://raw.githubusercontent.com/%s/%s/images/%s" % (
        REPO, COMMIT, urllib.parse.quote(name))


def candidate_names(lineara_id):
    """The file names this face might have, drawing before photograph."""
    return [
        "%s-%s%s" % (lineara_id, stem, suffix)
        for stem in KINDS.values()
        for suffix in (".jpg", ".png")
    ]


def wanted(db_path=builder.DB_PATH, min_signs=2):
    """The lineara.xyz ids of the faces that get a full page."""
    conn = sqlite3.connect(str(db_path))
    try:
        rows = conn.execute(
            """SELECT id, raw FROM inscriptions
                WHERE (SELECT coalesce(sum(n_signs), 0) FROM runs
                        WHERE inscription_id = inscriptions.id) >= ?""", (min_signs,)).fetchall()
    finally:
        conn.close()
    ids = []
    for iid, raw in rows:
        lineara_id = (json.loads(raw).get("lineara_id") if raw else None) or iid.replace(" ", "")
        ids.append(lineara_id)
    return sorted(set(ids))


def load_absent(path=None, commit=COMMIT):
    """Names known not to exist upstream at this commit."""
    path = Path(path or ABSENT_PATH)
    try:
        with open(path, encoding="utf-8") as f:
            doc = json.load(f)
    except (OSError, ValueError):
        return set()
    if doc.get("repo") != REPO or doc.get("commit") != commit:
        return set()  # a different pin: what was absent there says nothing here
    return set(doc.get("absent") or [])


def save_absent(absent, path=None, commit=COMMIT):
    path = Path(path or ABSENT_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    doc = {
        "repo": REPO,
        "commit": commit,
        "note": "Candidate file names that 404 at this commit. Generated by "
                "`python3 -m lineara images fetch`; delete to re-probe.",
        "absent": sorted(absent),
    }
    path.write_text(json.dumps(doc, indent=1) + "\n", encoding="utf-8")


def _download(name, dest, force):
    path = dest / name
    if path.exists() and not force:
        return "have"
    try:
        with urllib.request.urlopen(_url(name), timeout=60) as response:
            data = response.read()
    except urllib.error.HTTPError as error:
        # Most faces have only some of the four candidate names.
        return "missing" if error.code == 404 else "error"
    except OSError:
        return "error"
    if not data:
        return "error"
    tmp = path.with_suffix(path.suffix + ".part")
    tmp.write_bytes(data)
    tmp.replace(path)
    return "new"


def fetch(db_path=builder.DB_PATH, dest=IMAGE_SOURCE, force=False, workers=8, log=print,
          absent_path=None):
    dest = Path(dest)
    dest.mkdir(parents=True, exist_ok=True)
    names = [name for lineara_id in wanted(db_path) for name in candidate_names(lineara_id)]
    absent = set() if force else load_absent(absent_path)
    todo = [n for n in names if n not in absent]
    log("checking %d candidate files from %s@%s (%d known absent, not requested)"
        % (len(todo), REPO, COMMIT[:12], len(names) - len(todo)))

    counts = {"new": 0, "have": 0, "missing": 0, "error": 0}
    counts["missing"] = len(names) - len(todo)
    with ThreadPoolExecutor(max_workers=workers) as pool:
        for name, outcome in zip(todo, pool.map(lambda n: _download(n, dest, force), todo)):
            counts[outcome] += 1
            if outcome == "missing":
                absent.add(name)
    save_absent(absent, absent_path)

    (dest / STAMP).write_text(
        "Linear A inscription images\n"
        "===========================\n"
        "Source:  https://github.com/%s at %s\n"
        "Fetched: python3 -m lineara images fetch\n\n"
        "RIGHTS: recorded upstream as \"(c) Ecole Francaise d'Athenes\", from the\n"
        "GORILA volumes. Held here for local work. Publishing them is\n"
        "redistribution and needs the EFA's permission. This directory is under\n"
        "data/upstream/, which is gitignored.\n" % (REPO, COMMIT), encoding="utf-8")

    log("images: %d downloaded, %d already present, %d not published upstream%s"
        % (counts["new"], counts["have"], counts["missing"],
           ", %d failed" % counts["error"] if counts["error"] else ""))
    if counts["error"]:
        raise SystemExit("%d downloads failed; re-run to retry" % counts["error"])
    return counts
